services:
  vulnlab:
    build: .
    container_name: vulnlab
    ports:
      - "0.0.0.0:5000:5000"
    networks:
      vulnlab_net:
        ipv4_address: 172.20.10.100
    volumes:
      - vulnlab_data:/app/data
      - vulnlab_uploads:/app/uploads
    restart: unless-stopped

networks:
  vulnlab_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.10.0/24
          gateway: 172.20.10.1

volumes:
  vulnlab_data:
  vulnlab_uploads:
